# Generated by Django 3.2.12 on 2022-03-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('isVegan', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='spiceroom/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('items', models.TextField()),
                ('steps', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='spiceroom/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiceroom.category')),
            ],
        ),
    ]
