# Generated by Django 3.2.12 on 2022-03-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiceroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
