# Generated by Django 3.2.12 on 2022-03-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceroom', '0002_rename_recipes_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
